---
kind/action:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*.yml"

kind/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "**/*.md"

kind/go:
  - changed-files:
      - any-glob-to-any-file: "**/*.go"

kind/just:
  - changed-files:
      - any-glob-to-any-file: "**/justfile"
      - any-glob-to-any-file: "**/*.just"

kind/yaml:
  - changed-files:
      - any-glob-to-any-file: ["**/*.yaml", "**/*.yml"]
        all-globs-to-all-files: "!.github/**"

test/unit:
  - changed-files:
      - any-glob-to-any-file: "**/*_test.go"
