// Code generated by MockGen. DO NOT EDIT.
// Source: renderer.go
//
// Generated by this command:
//
//	mockgen -source=renderer.go -destination=renderer.gen_test.go -package=orchestrator
//

// Package orchestrator is a generated GoMock package.
package orchestrator

import (
	reflect "reflect"

	engine "github.com/osapi-io/osapi-orchestrator/internal/engine"
	gomock "go.uber.org/mock/gomock"
)

// Mockrenderer is a mock of renderer interface.
type Mockrenderer struct {
	ctrl     *gomock.Controller
	recorder *MockrendererMockRecorder
	isgomock struct{}
}

// MockrendererMockRecorder is the mock recorder for Mockrenderer.
type MockrendererMockRecorder struct {
	mock *Mockrenderer
}

// NewMockrenderer creates a new mock instance.
func NewMockrenderer(ctrl *gomock.Controller) *Mockrenderer {
	mock := &Mockrenderer{ctrl: ctrl}
	mock.recorder = &MockrendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrenderer) EXPECT() *MockrendererMockRecorder {
	return m.recorder
}

// LevelDone mocks base method.
func (m *Mockrenderer) LevelDone(level, changed, total int, mode levelMode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LevelDone", level, changed, total, mode)
}

// LevelDone indicates an expected call of LevelDone.
func (mr *MockrendererMockRecorder) LevelDone(level, changed, total, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LevelDone", reflect.TypeOf((*Mockrenderer)(nil).LevelDone), level, changed, total, mode)
}

// LevelStart mocks base method.
func (m *Mockrenderer) LevelStart(level int, tasks []string, mode levelMode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LevelStart", level, tasks, mode)
}

// LevelStart indicates an expected call of LevelStart.
func (mr *MockrendererMockRecorder) LevelStart(level, tasks, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LevelStart", reflect.TypeOf((*Mockrenderer)(nil).LevelStart), level, tasks, mode)
}

// PlanDone mocks base method.
func (m *Mockrenderer) PlanDone(report *Report) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlanDone", report)
}

// PlanDone indicates an expected call of PlanDone.
func (mr *MockrendererMockRecorder) PlanDone(report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanDone", reflect.TypeOf((*Mockrenderer)(nil).PlanDone), report)
}

// PlanStart mocks base method.
func (m *Mockrenderer) PlanStart(summary engine.PlanSummary) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlanStart", summary)
}

// PlanStart indicates an expected call of PlanStart.
func (mr *MockrendererMockRecorder) PlanStart(summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanStart", reflect.TypeOf((*Mockrenderer)(nil).PlanStart), summary)
}

// TaskDone mocks base method.
func (m *Mockrenderer) TaskDone(result engine.TaskResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TaskDone", result)
}

// TaskDone indicates an expected call of TaskDone.
func (mr *MockrendererMockRecorder) TaskDone(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDone", reflect.TypeOf((*Mockrenderer)(nil).TaskDone), result)
}

// TaskRetry mocks base method.
func (m *Mockrenderer) TaskRetry(name string, attempt int, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TaskRetry", name, attempt, err)
}

// TaskRetry indicates an expected call of TaskRetry.
func (mr *MockrendererMockRecorder) TaskRetry(name, attempt, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskRetry", reflect.TypeOf((*Mockrenderer)(nil).TaskRetry), name, attempt, err)
}

// TaskSkip mocks base method.
func (m *Mockrenderer) TaskSkip(name, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TaskSkip", name, reason)
}

// TaskSkip indicates an expected call of TaskSkip.
func (mr *MockrendererMockRecorder) TaskSkip(name, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskSkip", reflect.TypeOf((*Mockrenderer)(nil).TaskSkip), name, reason)
}

// TaskStart mocks base method.
func (m *Mockrenderer) TaskStart(name, detail string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TaskStart", name, detail)
}

// TaskStart indicates an expected call of TaskStart.
func (mr *MockrendererMockRecorder) TaskStart(name, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskStart", reflect.TypeOf((*Mockrenderer)(nil).TaskStart), name, detail)
}
